### ISSUE TITLE
repeated ScriptDevice output from RecordingSurface

### ISSUE THREAD

**Issue by pdknsk** [pygobject/pycairo#49] opened 2017-07-10 23:04 UTC
I'm not sure if there's a bug here, and if it's in ```pycairo```.

Take this code which produces the same image at two different device scales, and works as expected.
```Python
# A
for scale in (1, 2):
    device = cairo.ScriptDevice('A.%ix.txt' % scale)
    surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 100 * scale, 100 * scale)
    script_surface = cairo.ScriptSurface.create_for_target(device, surface)
    script_surface.set_device_scale(scale, scale)
    ctx = cairo.Context(script_surface)
    ctx.set_source_rgb(0.1, 0.2, 0.3)
    ctx.arc(50, 50, 25, 0, 360 * math.pi / 180)
    ctx.fill()
    script_surface.write_to_png('A.%ix.png' % scale)
```
Now for complex operations, it's more efficient to record and replay the surface. Strangely, this produces marginally different files at *scale > 1*. I added `ScriptSurface` precisely to debug this, but it doesn't quite work as expected here.
```Python
# B
recording_surface = cairo.RecordingSurface(cairo.Content.COLOR_ALPHA, 
    (0, 0, 100, 100))
ctx = cairo.Context(recording_surface)
ctx.set_source_rgb(0.1, 0.2, 0.3)
ctx.arc(50, 50, 25, 0, 360 * math.pi / 180)
ctx.fill()

for scale in (1, 2):
    device = cairo.ScriptDevice('B.%ix.txt' % scale)
    surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 100 * scale, 100 * scale)
    script_surface = cairo.ScriptSurface.create_for_target(device, surface)
    script_surface.set_device_scale(scale, scale)
    ctx = cairo.Context(script_surface)
    ctx.set_source_surface(recording_surface, 0, 0)
    ctx.paint()
    script_surface.write_to_png('B.%ix.png' % scale)
```
And the recorded scripts.
```
(A.1x.txt)

%!CairoScript
<< /content //COLOR_ALPHA /width 100 /height 100 >> surface context
0.1 0.2 0.3 rgb set-source
n 75 50 m 75 63.808594 63.808594 75 50 75 c 36.191406 75 25 63.808594 25 50 c 25 36.191406 36.191406 25 50 25 c 63.808594 25 75 36.191406 75 50 c
fill+
pop
```
```
(A.2x.txt)

%!CairoScript
<< /content //COLOR_ALPHA /width 200 /height 200 >> surface context
0.1 0.2 0.3 rgb set-source
n 150 100 m 150 127.613281 127.613281 150 100 150 c 72.386719 150 50 127.613281 50 100 c 50 72.386719 72.386719 50 100 50 c 127.613281 50 150 72.386719 150 100 c
fill+
pop
```
```
(B.1x.txt)

%!CairoScript
<< /content //COLOR_ALPHA /width 100 /height 100 >> surface context
//COLOR_ALPHA [0 0 100 100] record
dup /s9 exch def dup context
0.1 0.2 0.3 rgb set-source
n 75 50 m 75 63.808594 63.808594 75 50 75 c 36.191406 75 25 63.808594 25 50 c 25 36.191406 36.191406 25 50 25 c 63.808594 25 75 36.191406 75 50 c
fill+
pop pattern
  set-source
paint
pop
/s9 undef
```
```
(B.2x.txt)

%!CairoScript
<< /content //COLOR_ALPHA /width 200 /height 200 >> surface context
s9pattern
  [0.5 0 0 0.5 0 0] set-matrix
  set-source
paint
pop
```
I haven't tried to replay any, but *B.2x.txt* does obviously not have enough information to be successfully replayed, nor does it help in debugging. I expected numbers to compare.

**Comment by lazka** [comment] 2017-07-11 06:47
Thanks. Not sure where the problem is, will have a look later.

It's net scale related if I'm not mistaken:

```
# B
import cairo, math, io
recording_surface = cairo.RecordingSurface(cairo.Content.COLOR_ALPHA, (0, 0, 100, 100))
ctx = cairo.Context(recording_surface)
ctx.set_source_rgb(0.1, 0.2, 0.3)
ctx.paint()

output = []
for i in (1, 2):
    f = io.BytesIO()
    device = cairo.ScriptDevice(f)
    surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, 100, 100)
    script_surface = cairo.ScriptSurface.create_for_target(device, surface)
    ctx = cairo.Context(script_surface)
    ctx.set_source_surface(recording_surface, 0, 0)
    ctx.paint()
    device.flush()
    output.append(f.getvalue())

assert output[0] == output[1], output
```

**Comment by lazka** [comment] 2017-07-11 10:33
I get the same output using C:

```
// gcc example.c -o example $(pkg-config --cflags --libs cairo)
#include <cairo/cairo.h>
#include <cairo/cairo-script.h>
#include <stdlib.h>

int main(void) {
    cairo_t *ctx;
    cairo_surface_t * rec;
    cairo_device_t *dev1, *dev2;
    cairo_surface_t *script1, *script2;

    rec = cairo_recording_surface_create(CAIRO_CONTENT_COLOR_ALPHA, NULL);
    ctx = cairo_create(rec);
    cairo_set_source_rgb(ctx, 0.25, 0.5, 0.75);
    cairo_paint(ctx);
    cairo_destroy(ctx);

    dev1 = cairo_script_create("1.txt");
    script1 = cairo_script_surface_create(dev1, CAIRO_CONTENT_COLOR_ALPHA, 100, 100);
    ctx = cairo_create(script1);
    cairo_set_source_surface(ctx, rec, 0, 0);
    cairo_paint(ctx);
    cairo_destroy(ctx);
    cairo_device_destroy(dev1);
    cairo_surface_destroy(script1);

    dev2 = cairo_script_create("2.txt");
    script2 = cairo_script_surface_create(dev2, CAIRO_CONTENT_COLOR_ALPHA, 100, 100);
    ctx = cairo_create(script2);
    cairo_set_source_surface(ctx, rec, 0, 0);
    cairo_paint(ctx);
    cairo_destroy(ctx);
    cairo_device_destroy(dev2);
    cairo_surface_destroy(script2);

    cairo_surface_destroy(rec);

    return 0;
}
```

**Comment by lazka** [comment] 2017-07-11 10:39
Filed upstream: https://bugs.freedesktop.org/show_bug.cgi?id=101751

**Comment by lazka** [comment] 2017-07-11 18:23
Looks like this was acknowledged upstream, so I'm closing this here.

**Closed by lazka** 2017-07-11 18:23 UTC
Labels: upstream-bug

**Comment by pdknsk** [comment] 2017-07-12 16:52
​Thanks for filing the bug.​
