### ISSUE TITLE
error import cairo in python3.6

### ISSUE THREAD

**Issue by jozi** [pygobject/pycairo#105] opened 2018-03-12 10:57 UTC
error import cairo in python3.6
```
Traceback (most recent call last):
  File "/home/my.py", line 4, in <module>
    import cairo
  File "/home/tt/anaconda3/lib/python3.6/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/tt/anaconda3/lib/python3.6/site-packages/cairo/_cairo.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index

```

**Comment by lazka** [comment] 2018-03-12 11:03
Thanks. Please report to anaconda, looks like your cairo is different to what pycairo was built against.

**Comment by lazka** [comment] 2018-03-12 11:04
(or rebuild pycairo, I don't know how anaconda works)

**Comment by nanshihui** [comment] 2018-06-27 15:13
i got the same error . when i used in centos.
`
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from rotatetool import create_word
  File "/export/wireless_safe/digital_mark/rotatetool.py", line 2, in <module>
    import cairo
  File "/usr/local/python-2.7.15/lib/python2.7/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /usr/local/python-2.7.15/lib/python2.7/site-packages/cairo/_cairo.so: undefined symbol: cairo_region_destroy
`

**Comment by lazka** [comment] 2018-07-02 22:05
centos 7?

**Comment by nanshihui** [comment] 2018-07-11 03:41
centos 6.5

**Comment by nanshihui** [comment] 2018-07-11 03:42
i finally change the version of cairo , and  add environment , it worked

**Comment by lazka** [comment] 2018-07-11 03:45
yeah, centos 6.5 doesn't have a new enough cairo..

**Comment by arlejeun** [comment] 2018-08-06 14:57
I'm trying to install beeware on my virtual environment venv - Linux Ubuntu 16.04.
`python3 -m venv venv
. venv/bin/activate
pip install beeware`

During the installation, I get this error on my
`ImportError: /home/alejeune/Development/beeware/pycon/venv/lib/python3.6/site-packages/cairo/_cairo.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index`

See below the command highlited in my terminal
`Command "/home/alejeune/Development/beeware/pycon/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yqr0u95l/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3kdlzyar/install-record.txt --single-version-externally-managed --compile --install-headers /home/alejeune/Development/beeware/pycon/venv/include/site/python3.6/pygobject" failed with error code 1 in /tmp/pip-install-yqr0u95l/pygobject/
`
Can you please suggest how to address this issue? I'm new with Cairo

Thanks

**Comment by lazka** [comment] 2018-08-06 15:02
thanks, I'll try to reproduce.

**Comment by lazka** [comment] 2018-08-06 15:03
@arlejeun how did you install python3.6 on your Ubuntu 16.04?

**Comment by arlejeun** [comment] 2018-08-06 15:54
@lazka `sudo apt-get install python3.6`

**Comment by lazka** [comment] 2018-08-06 16:06
@arlejeun python3.6 isn't in xenial: https://packages.ubuntu.com/artful/python3.6

**Comment by arlejeun** [comment] 2018-08-06 16:12
@lazka I followed these instructions.
Install python 3.6 on Ubuntu 16.04 from PPA
https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get

`sudo add-apt-repository ppa:jonathonf/python-3.6`
`sudo apt update`
`sudo apt install python3.6`

**Comment by lazka** [comment] 2018-08-07 18:01
"pip install beeware" works fine here using the python3.6 from that ppa on 16.04.

What's your output of `apt show libcairo2`?

**Comment by arlejeun** [comment] 2018-08-07 18:08
(venv) alejeune@home:~/Development/beeware/pycon$ apt show libcairo2

Package: libcairo2
Version: 1.14.6-1
Priority: optional
Section: libs
Source: cairo
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,296 kB
Depends: libc6 (>= 2.14), libfontconfig1 (>= 2.9.0), libfreetype6 (>= 2.3.5), libpixman-1-0 (>= 0.30.0), libpng12-0 (>= 1.2.13-4), libx11-6, libxcb-render0, libxcb-shm0, libxcb1 (>= 1.6), libxext6, libxrender1, zlib1g (>= 1:1.1.4)
Breaks: libwebkit2gtk-3.0-25 (<< 2.4.5-2~), libwebkitgtk-1.0-0 (<< 2.4.5-2~), libwebkitgtk-3.0-0 (<< 2.4.5-2~), weston (<< 1.5.0-3~)
Homepage: http://cairographics.org/
Task: ubuntu-desktop, ubuntu-usb, print-server, kubuntu-desktop, edubuntu-desktop, edubuntu-usb, xubuntu-core, xubuntu-desktop, mythbuntu-frontend, mythbuntu-desktop, mythbuntu-backend-slave, mythbuntu-backend-master, lubuntu-core, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntu-gnome-desktop, ubuntu-sdk-libs, ubuntu-touch, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-mate-cloudtop
Supported: 5y
Download-Size: 555 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Description: Cairo 2D vector graphics library
 Cairo is a multi-platform library providing anti-aliased
 vector-based rendering for multiple target backends. Paths consist
 of line segments and cubic splines and can be rendered at any width
 with various join and cap styles. All colors may be specified with
 optional translucence (opacity/alpha) and combined using the
 extended Porter/Duff compositing algebra as found in the X Render
 Extension.
 .
 Cairo exports a stateful rendering API similar in spirit to the path
 construction, text, and painting operators of PostScript, (with the
 significant addition of translucence in the imaging model). When
 complete, the API is intended to support the complete imaging model of
 PDF 1.4.
 .
 This package contains the shared libraries.

**Comment by lazka** [comment] 2018-08-08 06:26
Thanks, that looks ok.

My last guess is that some old pycairo wheel built against some older cairo version is cached and reused. Try deleting "~/.cache/pip" and recreating the virtualenv.

**Comment by arlejeun** [comment] 2018-08-08 13:16
Thank you @lazka for your suggestion. Unfortunately, I followed those steps without success. 
Glad to hear it's working on your side. It is probably an issue on my environment.
I will re-install python but I doubt it makes a difference. Do you think using a GPU instead of a CPU might be the source of this issue? I will let you know if I find a way to fix it. Thanks.

**Comment by arlejeun** [comment] 2018-08-08 20:27
Failed building wheel for pygobject
  Running setup.py clean for pygobject
Failed to build pycairo pygobject
Installing collected packages: pycairo, gbulb, travertino, toga-core, pygobject, toga-gtk, toga, pip, setuptools, voc, jmespath, six, python-dateutil, docutils, botocore, s3transfer, boto3, chardet, idna, certifi, urllib3, requests, MarkupSafe, jinja2, whichcraft, arrow, jinja2-time, poyo, binaryornot, click, future, cookiecutter, briefcase, beeware
  Running setup.py install for pycairo ... error
    Complete output from command /home/alejeune/Development/beeware/3.6/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a9p1s2zx/pycairo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f5xn0jje-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/alejeune/Development/beeware/3.6/venv/include/site/python3.6/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.6/cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cairo
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=17 -DPYCAIRO_VERSION_MICRO=1 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/home/alejeune/Development/beeware/3.6/venv/include -I/usr/include/python3.6m -c cairo/device.c -o build/temp.linux-x86_64-3.6/cairo/device.o -Wall -Warray-bounds -Wcast-align -Wconversion -Wdeclaration-after-statement -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-security -Wimplicit-function-declaration -Winit-self -Winline -Wmissing-format-attribute -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wundef -Wunused-but-set-variable -Wswitch-default -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-command-line-argument -fno-strict-aliasing -fvisibility=hidden
    cairo/device.c:30:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/alejeune/Development/beeware/3.6/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a9p1s2zx/pycairo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f5xn0jje-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/alejeune/Development/beeware/3.6/venv/include/site/python3.6/pycairo" failed with error code 1 in /tmp/pip-build-a9p1s2zx/pycairo/

**Comment by arlejeun** [comment] 2018-08-08 20:35
@lazka - I was so frustrated that it works on your environment and not mine, I decided to uninstall python and re-install it.

Interestingly, when I create a virtual env with python 3 (python 3.5.2), i can install beeware successfully
`python3 -m venv venv`
`. venv/bin/activate`
`pip install beeware`

But when I want to create a virtual env from python 3.6 in a different folder, it failed
`python3.6 -m venv venv`
`. venv/bin/activate`
`pip install beeware`

See below the outcomes with python 3.6

  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pygobject pycairo
Installing collected packages: gbulb, travertino, toga-core, pycairo, pygobject, toga-gtk, toga, setuptools, MarkupSafe, jinja2, poyo, chardet, idna, urllib3, certifi, requests, whichcraft, click, binaryornot, six, python-dateutil, arrow, jinja2-time, future, cookiecutter, voc, jmespath, docutils, botocore, s3transfer, boto3, pip, briefcase, beeware
  Running setup.py install for pycairo ... error
    Complete output from command /home/alejeune/Development/beeware/3.6/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3y686jzw/pycairo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dz33sze7-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/alejeune/Development/beeware/3.6/venv/include/site/python3.6/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.6/cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cairo
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=17 -DPYCAIRO_VERSION_MICRO=1 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/home/alejeune/Development/beeware/3.6/venv/include -I/usr/include/python3.6m -c cairo/device.c -o build/temp.linux-x86_64-3.6/cairo/device.o -Wall -Warray-bounds -Wcast-align -Wconversion -Wdeclaration-after-statement -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-security -Wimplicit-function-declaration -Winit-self -Winline -Wmissing-format-attribute -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wundef -Wunused-but-set-variable -Wswitch-default -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-command-line-argument -fno-strict-aliasing -fvisibility=hidden
    cairo/device.c:30:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/alejeune/Development/beeware/3.6/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3y686jzw/pycairo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dz33sze7-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/alejeune/Development/beeware/3.6/venv/include/site/python3.6/pycairo" failed with error code 1 in /tmp/pip-build-3y686jzw/pycairo/

**Comment by lazka** [comment] 2018-08-09 04:47
you're missing the python3.6-dev package

**Comment by arlejeun** [comment] 2018-08-09 14:11
Thank you @lazka ! It works ..

For people facing the same issue, I ran this command
`sudo apt-get install python3.6-dev`

**Comment by lazka** [comment] 2018-08-09 14:17
So, you mean installing pycairo worked as well?

**Comment by arlejeun** [comment] 2018-08-09 18:39
Yes. It worked.

**Comment by lazka** [comment] 2018-08-10 06:32
ok, thanks, closing then.

**Closed by lazka** 2018-08-10 06:32 UTC
Labels: needinfo

**Comment by harisankarh** [comment] 2019-02-04 04:59
> Yes. It worked.

It worked for python 2.7 too.
had to install python2.7-dev // sudo apt-get install python2.7-dev
